FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 5173
ENV PORT 5173

CMD ["sh", "-lc", "npm run preview -- --host 0.0.0.0 --port ${PORT:-5173}"]